export const drillDownTable = {
    displayCol: [
        {
            className: "classPO",
            data: "po",
            dataAlign: "left",
            dataType: "string",
            headerAlign: "left",
            sort: true,
            title: "PO",
            visibility: "visible",
        },
        {
            className: "classSuppliers",
            data: "supplierName",
            dataAlign: "left",
            dataType: "string",
            headerAlign: "left",
            sort: true,
            title: "Supplier",
            visibility: "visible",
        },
        {
            className: "classDueDate",
            data: "dueDate",
            dataAlign: "left",
            dataType: "date",
            headerAlign: "left",
            sort: true,
            title: "Origial Due Date",
            visibility: "visible",
        },
        {
            className: "classPartNumber",
            data: "pn",
            dataAlign: "left",
            dataType: "string",
            headerAlign: "left",
            sort: true,
            title: "Part Number",
            visibility: "visible",
        },
        {
            className: "classPoLine",
            data: "poLineNum",
            dataAlign: "left",
            dataType: "number",
            headerAlign: "left",
            sort: true,
            title: "PO Line",
            visibility: "visible",
        },
        {
            className: "classOrderedQty",
            data: "openQty",
            dataAlign: "left",
            dataType: "number",
            headerAlign: "left",
            sort: true,
            title: "Ordered Qty",
            visibility: "visible",
        }
    ]
};